`timescale 1ns / 1ps

module top_lms_system(
    input wire clk,       
    input wire rst_btn    // Mapped to Switch V17
    );

    // Signals
    reg [9:0] rom_addr;
    wire [31:0] rom_data;
    
    wire signed [15:0] d_in;
    wire signed [15:0] x_in;
    wire signed [15:0] y_out;
    wire signed [15:0] e_out;
    
    wire core_done;
    reg core_start;
    
    // Memory (Generated by Python)
    rom_data u_memory (
        .clk(clk),
        .addr(rom_addr),
        .data(rom_data)
    );

    // Unpack: Upper 16 is Desired, Lower 16 is Reference
    assign d_in = rom_data[31:16]; 
    assign x_in = rom_data[15:0];

    // ILA Debug Core
    ila_0 u_ila (
        .clk(clk), 
        .probe0(e_out),
        .probe1(y_out),
        .probe2(d_in),
        .probe3(core_done)
    );

    // Main Control State Machine
    localparam S_READ = 0, S_WAIT = 1, S_PROCESS = 2;
    reg [1:0] state = S_READ;
    reg [3:0] latency_cnt;

    always @(posedge clk) begin
        if (rst_btn) begin
            rom_addr <= 0;
            core_start <= 0;
            state <= S_READ;
        end else begin
            case (state)
                S_READ: begin
                    // Address is set, wait for ROM access
                    latency_cnt <= 0;
                    state <= S_WAIT;
                end
                S_WAIT: begin
                    // Wait 2 cycles for ROM data to stabilize
                    if (latency_cnt == 1) begin 
                        core_start <= 1; // Trigger LMS Core
                        state <= S_PROCESS;
                    end else latency_cnt <= latency_cnt + 1;
                end
                S_PROCESS: begin
                    core_start <= 0; // Clear trigger
                    
                    // Wait here until OBC calculation is finished
                    if (core_done) begin
                        // Loop Forever Logic
                        if (rom_addr == 1023) 
                            rom_addr <= 0;
                        else 
                            rom_addr <= rom_addr + 1;
                            
                        state <= S_READ; // Fetch next sample
                    end
                end
            endcase
        end
    end

    // Instantiate OBC LMS Core
    lms_core #( .WIDTH(16), .FRAC(8) ) u_core (
        .clk(clk),
        .rst(rst_btn),
        .start(core_start),
        .x_in(x_in),
        .d_in(d_in),
        .y_out(y_out),
        .e_out(e_out),
        .done(core_done)
    );

endmodule